#!/bin/bash

# Remove cached outdated packages first from js node_modules
rm -rf modules/GUI/js/node_modules

# Keep use RenderingLibrary and it's still be part of source code 
cp -r node_modules/Mmsdk-apml-htmlrenderer/umd/ modules/GUI/RenderingLibrary/

# Brazil is copying the cached packages into package root directory
mv node_modules modules/GUI/js

# Copy UMD build artifacts to ApmlRenderer in node modules
cp -r modules/GUI/RenderingLibrary/ modules/GUI/js/node_modules/ApmlRenderer

npm run build --prefix modules/GUI/js