/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum CommandType {
    kCommandTypeArray = 0,
    kCommandTypeIdle = 1,
    kCommandTypeSequential = 2,
    kCommandTypeParallel = 3,
    kCommandTypeSendEvent = 4,
    kCommandTypeSetValue = 5,
    kCommandTypeSetState = 6,
    kCommandTypeSpeakItem = 7,
    kCommandTypeSpeakList = 8,
    kCommandTypeScroll = 9,
    kCommandTypeScrollToIndex = 10,
    kCommandTypeScrollToComponent = 11,
    kCommandTypeSelect = 12,
    kCommandTypeSetPage = 13,
    kCommandTypeAutoPage = 14,
    kCommandTypePlayMedia = 15,
    kCommandTypeControlMedia = 16,
    kCommandTypeOpenURL = 17,
    kCommandTypeAnimateItem = 18,
    kCommandTypeSetFocus = 19,
    kCommandTypeClearFocus = 20,
    kCommandTypeFinish = 21,
    kCommandTypeCustomEvent = 22
}
