/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum CommandScrollAlign {
    kCommandScrollAlignFirst = 0,
    kCommandScrollAlignCenter = 1,
    kCommandScrollAlignLast = 2,
    kCommandScrollAlignVisible = 3
}
