/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum CommandControlMedia {
    kCommandControlMediaPlay = 0,
    kCommandControlMediaPause = 1,
    kCommandControlMediaNext = 2,
    kCommandControlMediaPrevious = 3,
    kCommandControlMediaRewind = 4,
    kCommandControlMediaSeek = 5,
    kCommandControlMediaSetTrack = 6
}
