/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum ComponentType {
    kComponentTypeContainer = 0,
    kComponentTypeEditText = 1,
    kComponentTypeFrame = 2,
    kComponentTypeGridSequence = 3,
    kComponentTypeImage = 4,
    kComponentTypePager = 5,
    kComponentTypeScrollView = 6,
    kComponentTypeSequence = 7,
    kComponentTypeText = 8,
    kComponentTypeTouchWrapper = 9,
    kComponentTypeVectorGraphic = 10,
    kComponentTypeVideo = 11
}
