/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum GradientSpreadMethod {
    PAD = 0,
    REFLECT = 1,
    REPEAT = 2
}
