/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
export declare enum GraphicPropertyKey {
    kGraphicPropertyClipPath = 0,
    kGraphicPropertyCoordinateX = 1,
    kGraphicPropertyCoordinateY = 2,
    kGraphicPropertyFill = 3,
    kGraphicPropertyFillOpacity = 4,
    kGraphicPropertyFillTransform = 5,
    kGraphicPropertyFillTransformAssigned = 6,
    kGraphicPropertyFilters = 7,
    kGraphicPropertyFontFamily = 8,
    kGraphicPropertyFontSize = 9,
    kGraphicPropertyFontStyle = 10,
    kGraphicPropertyFontWeight = 11,
    kGraphicPropertyHeightActual = 12,
    kGraphicPropertyHeightOriginal = 13,
    kGraphicPropertyLetterSpacing = 14,
    kGraphicPropertyOpacity = 15,
    kGraphicPropertyPathData = 16,
    kGraphicPropertyPathLength = 17,
    kGraphicPropertyPivotX = 18,
    kGraphicPropertyPivotY = 19,
    kGraphicPropertyRotation = 20,
    kGraphicPropertyScaleX = 21,
    kGraphicPropertyScaleY = 22,
    kGraphicPropertyViewportHeightActual = 23,
    kGraphicPropertyViewportWidthActual = 24,
    kGraphicPropertyScaleTypeHeight = 25,
    kGraphicPropertyScaleTypeWidth = 26,
    kGraphicPropertyStroke = 27,
    kGraphicPropertyStrokeDashArray = 28,
    kGraphicPropertyStrokeDashOffset = 29,
    kGraphicPropertyStrokeLineCap = 30,
    kGraphicPropertyStrokeLineJoin = 31,
    kGraphicPropertyStrokeMiterLimit = 32,
    kGraphicPropertyStrokeOpacity = 33,
    kGraphicPropertyStrokeTransform = 34,
    kGraphicPropertyStrokeTransformAssigned = 35,
    kGraphicPropertyStrokeWidth = 36,
    kGraphicPropertyText = 37,
    kGraphicPropertyTextAnchor = 38,
    kGraphicPropertyTransform = 39,
    kGraphicPropertyTransformAssigned = 40,
    kGraphicPropertyTranslateX = 41,
    kGraphicPropertyTranslateY = 42,
    kGraphicPropertyVersion = 43,
    kGraphicPropertyViewportHeightOriginal = 44,
    kGraphicPropertyViewportWidthOriginal = 45,
    kGraphicPropertyWidthActual = 46,
    kGraphicPropertyWidthOriginal = 47
}
