/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum ImageScale {
    kImageScaleNone = 0,
    kImageScaleFill = 1,
    kImageScaleBestFill = 2,
    kImageScaleBestFit = 3,
    kImageScaleBestFitDown = 4
}
