/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum KeyboardType {
    kKeyboardTypeDecimalPad = 0,
    kKeyboardTypeEmailAddress = 1,
    kKeyboardTypeNormal = 2,
    kKeyboardTypeNumberPad = 3,
    kKeyboardTypePhonePad = 4,
    kKeyboardTypeUrl = 5
}
