/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum Navigation {
    kNavigationNormal = 0,
    kNavigationNone = 1,
    kNavigationWrap = 2,
    kNavigationForwardOnly = 3
}
