/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum VectorGraphicAlign {
    kVectorGraphicAlignBottom = 0,
    kVectorGraphicAlignBottomLeft = 1,
    kVectorGraphicAlignBottomRight = 2,
    kVectorGraphicAlignCenter = 3,
    kVectorGraphicAlignLeft = 4,
    kVectorGraphicAlignRight = 5,
    kVectorGraphicAlignTop = 6,
    kVectorGraphicAlignTopLeft = 7,
    kVectorGraphicAlignTopRight = 8
}
