/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum AnimationQuality {
    kAnimationQualityNone = 0,
    kAnimationQualitySlow = 1,
    kAnimationQualityNormal = 2
}
