/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/content/rootconfig.h line 44
 */
export declare enum AnimationQuality {
    kAnimationQualityNone = 0,
    kAnimationQualitySlow = 1,
    kAnimationQualityNormal = 2
}
