/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum AudioTrack {
    kAudioTrackBackground = 0,
    kAudioTrackForeground = 1,
    kAudioTrackNone = 2
}
