/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum CommandType {
    kCommandTypeIdle = 0,
    kCommandTypeSequential = 1,
    kCommandTypeParallel = 2,
    kCommandTypeSendEvent = 3,
    kCommandTypeSetValue = 4,
    kCommandTypeSetState = 5,
    kCommandTypeSpeakItem = 6,
    kCommandTypeSpeakList = 7,
    kCommandTypeScroll = 8,
    kCommandTypeScrollToIndex = 9,
    kCommandTypeScrollToComponent = 10,
    kCommandTypeSelect = 11,
    kCommandTypeSetPage = 12,
    kCommandTypeAutoPage = 13,
    kCommandTypePlayMedia = 14,
    kCommandTypeControlMedia = 15,
    kCommandTypeOpenURL = 16,
    kCommandTypeAnimateItem = 17,
    kCommandTypeSetFocus = 18,
    kCommandTypeClearFocus = 19,
    kCommandTypeFinish = 20,
    kCommandTypeCustomEvent = 21
}
