/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/command/commandproperties.h line 69
 */
export declare enum CommandControlMedia {
    kCommandControlMediaPlay = 0,
    kCommandControlMediaPause = 1,
    kCommandControlMediaNext = 2,
    kCommandControlMediaPrevious = 3,
    kCommandControlMediaRewind = 4,
    kCommandControlMediaSeek = 5,
    kCommandControlMediaSetTrack = 6
}
