/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum CommandAudioTrack {
    kCommandAudioTrackBackground = 0,
    kCommandAudioTrackForeground = 1,
    kCommandAudioTrackNone = 2
}
