/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/command/commandproperties.h line 46
 */
export declare enum CommandScrollAlign {
    kCommandScrollAlignFirst = 0,
    kCommandScrollAlignCenter = 1,
    kCommandScrollAlignLast = 2,
    kCommandScrollAlignVisible = 3
}
