/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/command/commandproperties.h line 53
 */
export declare enum CommandHighlightMode {
    kCommandHighlightModeLine = 0,
    kCommandHighlightModeBlock = 1
}
