/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/command/commandproperties.h line 24
 */
export declare enum CommandType {
    kCommandTypeIdle = 0,
    kCommandTypeSequential = 1,
    kCommandTypeParallel = 2,
    kCommandTypeSendEvent = 3,
    kCommandTypeSetValue = 4,
    kCommandTypeSetState = 5,
    kCommandTypeSpeakItem = 6,
    kCommandTypeSpeakList = 7,
    kCommandTypeScroll = 8,
    kCommandTypeScrollToIndex = 9,
    kCommandTypeScrollToComponent = 10,
    kCommandTypeSetPage = 11,
    kCommandTypeAutoPage = 12,
    kCommandTypePlayMedia = 13,
    kCommandTypeControlMedia = 14,
    kCommandTypeOpenURL = 15,
    kCommandTypeAnimateItem = 16,
    kCommandTypeSetFocus = 17,
    kCommandTypeClearFocus = 18
}
