/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum ComponentType {
    kComponentTypeContainer = 0,
    kComponentTypeFrame = 1,
    kComponentTypeImage = 2,
    kComponentTypePager = 3,
    kComponentTypeScrollView = 4,
    kComponentTypeSequence = 5,
    kComponentTypeText = 6,
    kComponentTypeTouchWrapper = 7,
    kComponentTypeVectorGraphic = 8,
    kComponentTypeVideo = 9
}
