/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum ContainerDirection {
    kContainerDirectionColumn = 0,
    kContainerDirectionRow = 1
}
