/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/engine/event.h line 133
 */
export declare enum EventProperty {
    kEventPropertyAlign = 0,
    kEventPropertyArguments = 1,
    kEventPropertyAudioTrack = 2,
    kEventPropertyCommand = 3,
    kEventPropertyComponent = 4,
    kEventPropertyComponents = 5,
    kEventPropertyDirection = 6,
    kEventPropertyHighlightMode = 7,
    kEventPropertyPosition = 8,
    kEventPropertySource = 9,
    kEventPropertyValue = 10
}
