/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/primitives/filter.h line 26
 */
export declare enum FilterType {
    kFilterTypeBlur = 0,
    kFilterTypeNoise = 1
}
