/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/component/componentproperties.h line 83
 */
export declare enum FlexboxAlign {
    kFlexboxAlignStretch = 0,
    kFlexboxAlignCenter = 1,
    kFlexboxAlignStart = 2,
    kFlexboxAlignEnd = 3,
    kFlexboxAlignBaseline = 4,
    kFlexboxAlignAuto = 5
}
