/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/component/componentproperties.h line 104
 */
export declare enum FlexboxJustifyContent {
    kFlexboxJustifyContentStart = 0,
    kFlexboxJustifyContentEnd = 1,
    kFlexboxJustifyContentCenter = 2,
    kFlexboxJustifyContentSpaceBetween = 3,
    kFlexboxJustifyContentSpaceAround = 4
}
