/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum FlexboxAlign {
    kFlexboxAlignStretch = 0,
    kFlexboxAlignCenter = 1,
    kFlexboxAlignStart = 2,
    kFlexboxAlignEnd = 3,
    kFlexboxAlignBaseline = 4,
    kFlexboxAlignAuto = 5
}
