/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum FontStyle {
    kFontStyleNormal = 0,
    kFontStyleItalic = 1
}
