/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/primitives/gradient.h line 35
 */
export declare enum GradientType {
    /** Linear gradient */
    LINEAR = 0,
    /** Radial gradient, centered about the center of an object */
    RADIAL = 1
}
