/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum GraphicPropertyKey {
    kGraphicPropertyFill = 0,
    kGraphicPropertyFillOpacity = 1,
    kGraphicPropertyHeightActual = 2,
    kGraphicPropertyHeightOriginal = 3,
    kGraphicPropertyOpacity = 4,
    kGraphicPropertyPathData = 5,
    kGraphicPropertyPivotX = 6,
    kGraphicPropertyPivotY = 7,
    kGraphicPropertyRotation = 8,
    kGraphicPropertyScaleX = 9,
    kGraphicPropertyScaleY = 10,
    kGraphicPropertyViewportHeightActual = 11,
    kGraphicPropertyViewportWidthActual = 12,
    kGraphicPropertyScaleTypeHeight = 13,
    kGraphicPropertyScaleTypeWidth = 14,
    kGraphicPropertyStroke = 15,
    kGraphicPropertyStrokeOpacity = 16,
    kGraphicPropertyStrokeWidth = 17,
    kGraphicPropertyTranslateX = 18,
    kGraphicPropertyTranslateY = 19,
    kGraphicPropertyVersion = 20,
    kGraphicPropertyViewportHeightOriginal = 21,
    kGraphicPropertyViewportWidthOriginal = 22,
    kGraphicPropertyWidthActual = 23,
    kGraphicPropertyWidthOriginal = 24
}
