/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/component/componentproperties.h line 43
 */
export declare enum ImageScale {
    kImageScaleNone = 0,
    kImageScaleFill = 1,
    kImageScaleBestFill = 2,
    kImageScaleBestFit = 3,
    kImageScaleBestFitDown = 4
}
