/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/component/componentproperties.h line 28
 */
export declare enum ImageAlign {
    kImageAlignBottom = 0,
    kImageAlignBottomLeft = 1,
    kImageAlignBottomRight = 2,
    kImageAlignCenter = 3,
    kImageAlignLeft = 4,
    kImageAlignRight = 5,
    kImageAlignTop = 6,
    kImageAlignTopLeft = 7,
    kImageAlignTopRight = 8
}
