/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/utils/log.h line 34
 */
export declare enum LogLevel {
    NONE = -1,
    TRACE = 0,
    DEBUG = 1,
    INFO = 2,
    WARN = 3,
    ERROR = 5,
    CRITICAL = 6
}
