/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/component/componentproperties.h line 140
 */
export declare enum Navigation {
    kNavigationNormal = 0,
    kNavigationNone = 1,
    kNavigationWrap = 2,
    kNavigationForwardOnly = 3
}
