/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/primitives/filter.h line 44
 */
export declare enum NoiseFilterKind {
    kFilterNoiseKindUniform = 0,
    kFilterNoiseKindGaussian = 1
}
