/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/component/componentproperties.h line 62
 */
export declare enum TextAlign {
    kTextAlignAuto = 0,
    kTextAlignLeft = 1,
    kTextAlignCenter = 2,
    kTextAlignRight = 3
}
