/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/component/componentproperties.h line 72
 */
export declare enum TextAlignVertical {
    kTextAlignVerticalAuto = 0,
    kTextAlignVerticalTop = 1,
    kTextAlignVerticalCenter = 2,
    kTextAlignVerticalBottom = 3
}
