/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/component/component.h line 44
 */
export declare enum UpdateType {
    /**
     * This component (generally a touch wrapper) has been "pressed" and should execute the
     * onPress commands.
     */
    kUpdatePressed = 0,
    /**
     * This component should take keyboard focus.
     */
    kUpdateTakeFocus = 1,
    /**
     * This component is being touched by the user.  This happens before the kUpdatePressed message.
     * Pass an non-zero argument (1) to indicate that there is a touch-down event in the component.
     * Pass a zero argument (0) to indicate that there is a touch-up or touch-exit event in the component.
     */
    kUpdatePressState = 2,
    /**
     * Update the current scroll position.  The argument is the updated scroll position in dp.
     * Scroll positions are non-negative.
     */
    kUpdateScrollPosition = 3,
    /**
     * A pager has been moved by the user.  The argument is the new page number (0-based index).
     */
    kUpdatePagerPosition = 4,
    /**
     * A pager has been moved in response to a SetPage event.  The argument is the new page number (0-based index).
     */
    kUpdatePagerByEvent = 5
}
