/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/component/componentproperties.h line 174
 */
export declare enum VectorGraphicScale {
    kVectorGraphicScaleNone = 0,
    kVectorGraphicScaleFill = 1,
    kVectorGraphicScaleBestFill = 2,
    kVectorGraphicScaleBestFit = 3
}
