/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum VectorGraphicScale {
    kVectorGraphicScaleNone = 0,
    kVectorGraphicScaleFill = 1,
    kVectorGraphicScaleBestFill = 2,
    kVectorGraphicScaleBestFit = 3
}
