/**
 * Copyright 2018 Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen from:
 * /private/tmp/vvv/src/apl-core-library-master/aplcore/include/apl/component/componentproperties.h line 159
 */
export declare enum VectorGraphicAlign {
    kVectorGraphicAlignBottom = 0,
    kVectorGraphicAlignBottomLeft = 1,
    kVectorGraphicAlignBottomRight = 2,
    kVectorGraphicAlignCenter = 3,
    kVectorGraphicAlignLeft = 4,
    kVectorGraphicAlignRight = 5,
    kVectorGraphicAlignTop = 6,
    kVectorGraphicAlignTopLeft = 7,
    kVectorGraphicAlignTopRight = 8
}
