/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 */
/**
 * AUTOGENERATED FILE. DO NOT MODIFY!
 * This file is autogenerated by enumgen.
 */
export declare enum VideoScale {
    kVideoScaleBestFill = 0,
    kVideoScaleBestFit = 1
}
